name: 'debug'

on:
  # push:
  pull_request:
  workflow_dispatch:
    inputs:
      pr_num:
        description: Pull Request Number (optional)
        required: false

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:

  debug:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        if: ${{ inputs.pr_num == '' }}
        uses: actions/checkout@v3

      - name: Checkout PR ${{ inputs.pr_num }}
        if: ${{ inputs.pr_num != '' }}
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ inputs.pr_num }}/merge"

      - run: |
          echo Dump GitHub context
          echo '${{ toJSON(github) }}'

      - run: |
          echo Dump job context
          echo '${{ toJSON(job) }}'

      - run: |
          echo Dump steps context
          echo '${{ toJSON(steps) }}'

      - run: |
          echo Dump runner context
          echo '${{ toJSON(runner) }}'

      - run: |
          echo Dump strategy context
          echo '${{ toJSON(strategy) }}'

      - run: |
          echo Dump matrix context
          echo '${{ toJSON(matrix) }}'


      - run: |
          echo Print all environment variables
          env
